		<h1>Facebook Test</h1>
		
		<div id="fb-root"></div>
		<script src="http://connect.facebook.net/en_US/all.js"></script>
        <script type="text/javascript">
            window.fbAsyncInit = function() {
                FB.init({appId: '<?php echo $this->options['appid']; ?>',
                status: true, 
                cookie: true, 
                xfbml: true,});
 
                /* All the events registered */
                FB.Event.subscribe('auth.login', function(response) {
                    // do something with response
                    login(response);
                });
                FB.Event.subscribe('auth.logout', function(response) {
                    // do something with response
                    logout();
                });
            };
            (function() {
                var e = document.createElement('script');
                e.type = 'text/javascript';
                e.src = document.location.protocol +
                    '//connect.facebook.net/en_US/all.js';
                e.async = true;
                document.getElementById('fb-root').appendChild(e);
            }());
 
            function login(response){
               if (response.session) {
			        var access_token = response.session.access_token;
			        alert(access_token);
			        document.cookie = 'fb_token=' + access_token;
			    } 
            }
            function logout(){
            }
</script> 

    <p>
        <fb:login-button autologoutlink="true" perms="email,user_birthday,status_update,publish_stream, read_friendlists,friends_about_me, read_stream"></fb:login-button>
    </p>
	